### PR TITLE
Fix when Moving Event, Note/Event Becomes Duplicated

### LINKED ISSUE #961: When moving an event to some other time, it shows the previous note and event separately.
# steps to reproduce

Situation: You add a calendar event via Apple's Calendar app or Google Calendar or whatever. You see that the event has been synced in Hyprnote. You write up some quick notes to prepare for the meeting. You reschedule the meeting, and now you have two things showing up in your calendar view.

### PR DESCRIPTION
**Pull request by plyght**
fixes #961

### CODE REVIEW

File: crates/db-user/src/events_ops.rs [hunk 1]
```diff
@@ -26,6 +26,47 @@ impl UserDatabase {
         Ok(())
     }
 
+    pub async fn update_event(&self, event: Event) -> Result<Event, crate::Error> {
+        let conn = self.conn()?;
+        let event_id = event.id.clone();
+
+        let mut rows = conn
+            .query(
+                "UPDATE events SET
```
Comment (yujonglee) [inline crates/db-user/src/events_ops.rs:35]: Do we need update when we have upsert?

Comment (plyght) [reply crates/db-user/src/events_ops.rs:35]: @yujonglee yes, as they both serve different purposes...
`update_event` updates by the database id (used in Apple Calendar sync)
`upsert_event` updates by the `tracking_id` (used in data loading)
